name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: lawijdo201/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ 76cda1925cda12b066d06969b9a7eb08 }}
          TIMEZONE: Asia/Seoul
